# **what?**
# Return the list of supported adapters to test for the package
#
# **why?**
# To standardize the list of supported adapters across workflows


name: Supported Adapters
description: Get the list of supported adapters to test for the package

outputs:
  adapters:
    description: Supported adapters to test
    value: ${{ steps.supported-adapters.outputs.adapters }}


runs:
  using: "composite"

  steps:
      - name: "Checkout ${{ github.event.repository }}"
        uses: actions/checkout@v4
        with:
          # specifying the ref avoids checking out the repository in a detached state
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ inputs.GITHUB_TOKEN }}

      - name: "Set up Python ${{ env.PYTHON_VERSION }}"
        uses: actions/setup-python@v5
        with:
            python-version: ${{ env.PYTHON_VERSION }}

      - name: "Install tox"
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install tox

      - name: "Get list of supported adapters or use input adapter only"
        id: list-adapters
        shell: bash
        run: |
            if [ -z "${{ inputs.adapter }}" ]; then
                # github adds a pip freeze and a new line we need to strip out
                source supported_adapters.env
                echo $SUPPORTED_ADAPTERS
                echo "test_adapters=$SUPPORTED_ADAPTERS" >> $GITHUB_OUTPUT
            else
                echo "test_adapters=${{ inputs.adapter }}" >> $GITHUB_OUTPUT
            fi

      - name: "Format adapter list for use as the matrix"
        id: supported-adapters
        shell: bash
        run: |
            # Convert to JSON array and output
            supported_adapters=$(echo "${{ steps.list-adapters.outputs.test_adapters }}" | jq -Rc 'split(",")')
            echo $supported_adapters
            echo "adapters=$supported_adapters" >> $GITHUB_OUTPUT

      - name: "[ANNOTATION] ${{ github.event.repository.name }} - Testing ${{ steps.supported-adapters.outputs.adapters }}"
        shell: bash
        run: |
            title="${{ github.event.repository.name }} - adapters to test"
            message="The workflow will run tests for the following adapters: ${{ steps.supported-adapters.outputs.adapters }}"
            echo "::notice $title::$message"