# **what?**
# Run tests for the package using the supported adapters
#
# **why?**
# To standardize the list of supported adapters across workflows


name: Run Package Integration Tests
description: Run integration tests for the package using the supported adapters

inputs:
  adapter:
    description: 'Adapters to test - as json'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Checkout ${{ github.event.repository }} "
      uses: actions/checkout@v4
      with:
        # specifying the ref avoids checking out the repository in a detached state
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: "Set up Python 3.11"
      uses: actions/setup-python@v5
      with:
          python-version: "3.11"

    - name: "Install ${{ inputs.adapter }}"
      shell: bash
      run: |
          python -m pip install --upgrade pip
          pip install dbt-${{ inputs.adapter }}

    - name: "Install tox"
      shell: bash
      run: |
          python -m pip install --upgrade pip
          pip install tox

    - name: "Run integration tests with tox on ${{ inputs.adapter }}"
      shell: bash
      run: |
          tox -e dbt_integration_${{ inputs.adapter }}
      # postgres runs in the container, so nothing below is an actual secret
      env:
          POSTGRES_HOST: ${{ env.POSTGRES_HOST }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          DBT_ENV_SECRET_POSTGRES_PASS: ${{ env.DBT_ENV_SECRET_POSTGRES_PASS }}
          POSTGRES_PORT: ${{ env.POSTGRES_PORT }}
          POSTGRES_DATABASE: ${{ env.POSTGRES_DATABASE }}
          POSTGRES_SCHEMA: ${{ env.POSTGRES_SCHEMA }}
          # TODO: add the rest